'use client'

import { useState } from 'react'
import { ShieldCheck, Search } from 'lucide-react'
import { Panel, KpiCard, StatusBadge, TechButton } from '@/components/ade/primitives'
import { reports } from '@/lib/ade-data'
import { cn } from '@/lib/utils'

export function ReportsScreen() {
  const [selectedId, setSelectedId] = useState(reports[0].id)
  const selected = reports.find((r) => r.id === selectedId) ?? reports[0]

  return (
    <div className="grid h-full grid-cols-1 gap-6 lg:grid-cols-[minmax(0,300px)_1fr]">
      {/* Report list */}
      <Panel className="flex flex-col">
        <div className="border-b border-border p-3">
          <div className="relative">
            <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
            <input
              placeholder="Search reports..."
              aria-label="Search reports"
              className="h-9 w-full rounded-md border border-border bg-card pl-9 pr-3 text-sm text-foreground placeholder:text-muted-foreground focus:border-primary/50 focus:outline-none"
            />
          </div>
        </div>
        <ul className="flex-1 overflow-y-auto">
          {reports.map((r) => {
            const isSel = r.id === selectedId
            return (
              <li key={r.id}>
                <button
                  type="button"
                  onClick={() => setSelectedId(r.id)}
                  className={cn(
                    'flex w-full flex-col gap-2 border-b border-border px-4 py-3 text-left transition-colors last:border-b-0',
                    isSel ? 'bg-primary/10 ring-1 ring-inset ring-primary/40' : 'hover:bg-card',
                  )}
                >
                  <span className="text-sm font-medium text-foreground">{r.title}</span>
                  <div className="flex items-center justify-between font-mono text-[11px] text-muted-foreground">
                    <span>{r.date}</span>
                    <span>{r.findings} findings</span>
                  </div>
                </button>
              </li>
            )
          })}
        </ul>
      </Panel>

      {/* Report detail */}
      <div className="flex flex-col gap-6">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <StatusBadge tone="anomaly">Report_draft</StatusBadge>
            <h1 className="mt-2 text-2xl font-semibold tracking-tight text-foreground">{selected.title}</h1>
            <p className="mt-1 font-mono text-xs text-muted-foreground">
              {selected.project} · {selected.runId}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <TechButton variant="secondary">Markdown</TechButton>
            <TechButton variant="secondary">HTML</TechButton>
            <TechButton variant="secondary">JSON</TechButton>
            <TechButton variant="primary">Export</TechButton>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
          <KpiCard
            label="Findings"
            value={selected.findings}
            hint={`${selected.critical} critical`}
            hintTone="critical"
          />
          <KpiCard label="Novelty avg" value={selected.noveltyAvg.toFixed(2)} />
          <KpiCard label="Confidence" value={selected.confidence.toFixed(2)} />
          <KpiCard
            label="Status"
            value={`${selected.reviewed}/${selected.findings}`}
            hint="Reviewed"
            hintTone="operational"
          />
        </div>

        <Panel className="p-5">
          <h2 className="text-lg font-semibold text-foreground">Evidence Summary</h2>
          <div className="mt-4 rounded-md border border-border bg-card p-5">
            {selected.summary.split('\n\n').map((para, i) => (
              <p key={i} className={cn('text-sm leading-relaxed text-muted-foreground', i > 0 && 'mt-4')}>
                {para}
              </p>
            ))}
          </div>
        </Panel>

        <div>
          <p className="font-mono text-[11px] uppercase tracking-[0.14em] text-muted-foreground">
            Validation integrity
          </p>
          <div className="mt-2 flex flex-wrap items-center gap-3 rounded-md border border-border bg-card px-4 py-3">
            <ShieldCheck className="size-4 text-operational" />
            <span className="font-mono text-xs text-muted-foreground">
              SHA-256: {selected.hash} · GENERATED BY ADE_ENGINE_V0.1.0_L · TIMESTAMP: 1733667841
            </span>
          </div>
        </div>
      </div>
    </div>
  )
}
