"""Versioned contracts and reproducibility foundations for ADE visual workflows."""

from ade.visual.benchmark_artifacts import (
    publish_visual_benchmark_artifact,
    validate_visual_benchmark_artifact,
)
from ade.visual.benchmark_contracts import (
    VisualBenchmarkDatasetManifest,
    VisualBenchmarkLabel,
    VisualBenchmarkMetricSummary,
    VisualBenchmarkOperatingPointResult,
    VisualBenchmarkPrediction,
    VisualBenchmarkProvenance,
    VisualBenchmarkResult,
    VisualBenchmarkRunConfig,
    VisualBenchmarkSample,
    VisualBenchmarkSplit,
)
from ade.visual.benchmark_evaluation import evaluate_visual_benchmark
from ade.visual.benchmark_manifests import (
    deserialize_visual_benchmark_manifest,
    load_visual_benchmark_manifest,
    resolve_visual_benchmark_root,
    serialize_visual_benchmark_manifest,
    validate_visual_benchmark_manifest,
)

from ade.visual.calibration import (
    apply_calibration,
    build_calibration_result,
    evaluate_thresholds,
    fit_calibration,
    generate_threshold_candidates,
    summarize_scores,
)
from ade.visual.calibration_artifacts import (
    publish_calibration_artifact,
    validate_calibration_artifact,
)
from ade.visual.calibration_contracts import (
    CalibrationDatasetSummary,
    CalibrationMethodConfig,
    CalibrationProvenance,
    CalibrationResult,
    FittedCalibrationModel,
    OperatingPointSummary,
    ScoreDistributionSummary,
    ThresholdCandidate,
    ThresholdEvaluationResult,
)

from ade.visual.config import (
    VISUAL_ENGINE_SCHEMA_VERSION,
    VisualEngineConfig,
    VisualReferenceScoringConfig,
)
from ade.visual.contracts import (
    VisualArtifactManifest,
    VisualBackendCapabilities,
    VisualDatasetRole,
    VisualEngineRequest,
    VisualEngineResult,
    VisualExecutionMode,
    VisualReproducibilityManifest,
)
from ade.visual.coreset import CoresetSelection, select_reference_coreset
from ade.visual.errors import (
    VisualConfigurationError,
    VisualContractVersionError,
    VisualDatasetRoleError,
    VisualEngineError,
    VisualIntegrityError,
    VisualManifestError,
    VisualProvisioningError,
)
from ade.visual.exact_search import ExactNumpySearch, ReferenceSimilaritySearch
from ade.visual.fingerprints import (
    VisualDatasetFingerprint,
    VisualFileFingerprint,
    fingerprint_configuration,
    fingerprint_visual_content,
    fingerprint_visual_dataset,
    fingerprint_visual_directory,
    normalize_relative_path,
    sha256_file,
    sha256_stream,
)
from ade.visual.manifests import (
    deserialize_artifact_manifest,
    deserialize_reproducibility_manifest,
    read_artifact_manifest,
    read_reproducibility_manifest,
    serialize_artifact_manifest,
    serialize_reproducibility_manifest,
    validate_artifact_integrity,
    write_manifest,
)
from ade.visual.reference_builder import (
    ReferenceMemoryBuildSummary,
    build_reference_memory_from_images,
)
from ade.visual.reference_contracts import (
    REFERENCE_MEMORY_SCHEMA_VERSION,
    LoadedReferenceMemory,
    ReferenceMemoryManifest,
    ReferenceNeighbor,
    ReferenceSearchResult,
    ReferenceVectorRecord,
    validate_reference_records,
)
from ade.visual.reference_benchmark import run_reference_benchmark
from ade.visual.reference_memory import (
    build_reference_memory,
    derive_reference_memory_id,
    deserialize_reference_memory_manifest,
    load_reference_memory,
    serialize_reference_memory_manifest,
    validate_reference_memory,
)
from ade.visual.reference_scoring import score_reference_anomalies
from ade.visual.representation import (
    DINOv2ModelAdapter,
    DINOv2VisualRepresentationProvider,
    LightweightVisualRepresentationProvider,
    RepresentationBatch,
    RepresentationProviderConfig,
    RepresentationProviderMetadata,
    RepresentationRecord,
    VisualRepresentationProvider,
    create_visual_representation_provider,
)
from ade.visual.scoring_artifacts import publish_scoring_artifacts, validate_scoring_artifacts
from ade.visual.scoring_contracts import (
    ImageAnomalyScore,
    PatchAnomalyScore,
    QueryPatchRecord,
    ReferenceEvidence,
    ReferenceScoringProvenance,
    ReferenceScoringResult,
    ReferenceScoringSummary,
    SpatialAnomalyMap,
)
from ade.visual.search_backends import (
    ExactNumpySearchBackend,
    FaissBackendConfig,
    FaissIndexAdapter,
    FaissSearchBackend,
    SearchBackendConfig,
    SearchBackendMetadata,
    VisualSearchBackend,
    create_search_backend,
)
from ade.visual.spatial_maps import build_spatial_maps
from ade.visual.temporal_artifacts import (
    publish_temporal_change_artifact,
    validate_temporal_change_artifact,
)
from ade.visual.temporal_change import analyze_temporal_change
from ade.visual.temporal_contracts import (
    TemporalAlignmentSummary,
    TemporalChangeEvent,
    TemporalChangeProvenance,
    TemporalChangeResult,
    TemporalChangeScore,
    TemporalChangeSummary,
    TemporalObservation,
    TemporalObservationSequence,
    TemporalPatchEvidence,
)
from ade.visual.temporal_manifests import (
    deserialize_temporal_manifest,
    load_temporal_manifest,
    serialize_temporal_manifest,
    validate_temporal_manifest,
)

__all__ = [
    "VisualBenchmarkDatasetManifest",
    "VisualBenchmarkLabel",
    "VisualBenchmarkMetricSummary",
    "VisualBenchmarkOperatingPointResult",
    "VisualBenchmarkPrediction",
    "VisualBenchmarkProvenance",
    "VisualBenchmarkResult",
    "VisualBenchmarkRunConfig",
    "VisualBenchmarkSample",
    "VisualBenchmarkSplit",
    "CalibrationDatasetSummary",
    "CalibrationMethodConfig",
    "CalibrationProvenance",
    "CalibrationResult",
    "FittedCalibrationModel",
    "OperatingPointSummary",
    "ScoreDistributionSummary",
    "ThresholdCandidate",
    "ThresholdEvaluationResult",
    "VISUAL_ENGINE_SCHEMA_VERSION",
    "REFERENCE_MEMORY_SCHEMA_VERSION",
    "ReferenceMemoryBuildSummary",
    "LoadedReferenceMemory",
    "ExactNumpySearch",
    "CoresetSelection",
    "ReferenceMemoryManifest",
    "ReferenceNeighbor",
    "ReferenceSearchResult",
    "ReferenceSimilaritySearch",
    "ReferenceVectorRecord",
    "LightweightVisualRepresentationProvider",
    "DINOv2ModelAdapter",
    "DINOv2VisualRepresentationProvider",
    "ExactNumpySearchBackend",
    "FaissBackendConfig",
    "FaissIndexAdapter",
    "FaissSearchBackend",
    "SearchBackendConfig",
    "SearchBackendMetadata",
    "VisualSearchBackend",
    "RepresentationBatch",
    "RepresentationProviderConfig",
    "RepresentationProviderMetadata",
    "RepresentationRecord",
    "VisualRepresentationProvider",
    "QueryPatchRecord",
    "PatchAnomalyScore",
    "ImageAnomalyScore",
    "SpatialAnomalyMap",
    "ReferenceEvidence",
    "ReferenceScoringProvenance",
    "ReferenceScoringResult",
    "ReferenceScoringSummary",
    "VisualArtifactManifest",
    "VisualBackendCapabilities",
    "VisualConfigurationError",
    "VisualContractVersionError",
    "VisualDatasetRole",
    "VisualDatasetFingerprint",
    "VisualDatasetRoleError",
    "VisualEngineConfig",
    "VisualReferenceScoringConfig",
    "VisualEngineError",
    "VisualEngineRequest",
    "VisualEngineResult",
    "VisualExecutionMode",
    "VisualIntegrityError",
    "VisualManifestError",
    "VisualProvisioningError",
    "VisualReproducibilityManifest",
    "VisualFileFingerprint",
    "deserialize_artifact_manifest",
    "deserialize_reproducibility_manifest",
    "deserialize_reference_memory_manifest",
    "build_reference_memory",
    "build_reference_memory_from_images",
    "run_reference_benchmark",
    "derive_reference_memory_id",
    "fingerprint_configuration",
    "fingerprint_visual_content",
    "fingerprint_visual_dataset",
    "fingerprint_visual_directory",
    "normalize_relative_path",
    "load_reference_memory",
    "read_artifact_manifest",
    "read_reproducibility_manifest",
    "serialize_artifact_manifest",
    "serialize_reproducibility_manifest",
    "select_reference_coreset",
    "serialize_reference_memory_manifest",
    "sha256_file",
    "sha256_stream",
    "validate_artifact_integrity",
    "validate_reference_records",
    "validate_reference_memory",
    "write_manifest",
    "build_spatial_maps",
    "publish_scoring_artifacts",
    "score_reference_anomalies",
    "validate_scoring_artifacts",
    "create_visual_representation_provider",
    "create_search_backend",
    "apply_calibration",
    "build_calibration_result",
    "evaluate_thresholds",
    "fit_calibration",
    "generate_threshold_candidates",
    "publish_calibration_artifact",
    "summarize_scores",
    "validate_calibration_artifact",
    "deserialize_visual_benchmark_manifest",
    "evaluate_visual_benchmark",
    "load_visual_benchmark_manifest",
    "publish_visual_benchmark_artifact",
    "resolve_visual_benchmark_root",
    "serialize_visual_benchmark_manifest",
    "validate_visual_benchmark_artifact",
    "validate_visual_benchmark_manifest",
    "TemporalObservation",
    "TemporalObservationSequence",
    "TemporalAlignmentSummary",
    "TemporalChangeScore",
    "TemporalPatchEvidence",
    "TemporalChangeEvent",
    "TemporalChangeSummary",
    "TemporalChangeProvenance",
    "TemporalChangeResult",
    "serialize_temporal_manifest",
    "deserialize_temporal_manifest",
    "load_temporal_manifest",
    "validate_temporal_manifest",
    "analyze_temporal_change",
    "publish_temporal_change_artifact",
    "validate_temporal_change_artifact",
]
