"""Versioned contracts and reproducibility foundations for ADE visual workflows."""

from ade.visual.config import (
    VISUAL_ENGINE_SCHEMA_VERSION,
    VisualEngineConfig,
    VisualReferenceScoringConfig,
)
from ade.visual.contracts import (
    VisualArtifactManifest,
    VisualBackendCapabilities,
    VisualDatasetRole,
    VisualEngineRequest,
    VisualEngineResult,
    VisualExecutionMode,
    VisualReproducibilityManifest,
)
from ade.visual.coreset import CoresetSelection, select_reference_coreset
from ade.visual.errors import (
    VisualConfigurationError,
    VisualContractVersionError,
    VisualDatasetRoleError,
    VisualEngineError,
    VisualIntegrityError,
    VisualManifestError,
    VisualProvisioningError,
)
from ade.visual.exact_search import ExactNumpySearch, ReferenceSimilaritySearch
from ade.visual.fingerprints import (
    VisualDatasetFingerprint,
    VisualFileFingerprint,
    fingerprint_configuration,
    fingerprint_visual_dataset,
    fingerprint_visual_directory,
    normalize_relative_path,
    sha256_file,
    sha256_stream,
)
from ade.visual.manifests import (
    deserialize_artifact_manifest,
    deserialize_reproducibility_manifest,
    read_artifact_manifest,
    read_reproducibility_manifest,
    serialize_artifact_manifest,
    serialize_reproducibility_manifest,
    validate_artifact_integrity,
    write_manifest,
)
from ade.visual.reference_contracts import (
    REFERENCE_MEMORY_SCHEMA_VERSION,
    LoadedReferenceMemory,
    ReferenceMemoryManifest,
    ReferenceNeighbor,
    ReferenceSearchResult,
    ReferenceVectorRecord,
    validate_reference_records,
)
from ade.visual.reference_memory import (
    build_reference_memory,
    derive_reference_memory_id,
    deserialize_reference_memory_manifest,
    load_reference_memory,
    serialize_reference_memory_manifest,
    validate_reference_memory,
)
from ade.visual.reference_scoring import score_reference_anomalies
from ade.visual.representation import (
    LightweightVisualRepresentationProvider,
    RepresentationBatch,
    RepresentationProviderConfig,
    RepresentationProviderMetadata,
    RepresentationRecord,
    VisualRepresentationProvider,
    create_visual_representation_provider,
)
from ade.visual.scoring_artifacts import publish_scoring_artifacts, validate_scoring_artifacts
from ade.visual.scoring_contracts import (
    ImageAnomalyScore,
    PatchAnomalyScore,
    QueryPatchRecord,
    ReferenceEvidence,
    ReferenceScoringProvenance,
    ReferenceScoringResult,
    ReferenceScoringSummary,
    SpatialAnomalyMap,
)
from ade.visual.spatial_maps import build_spatial_maps

__all__ = [
    "VISUAL_ENGINE_SCHEMA_VERSION",
    "REFERENCE_MEMORY_SCHEMA_VERSION",
    "LoadedReferenceMemory",
    "ExactNumpySearch",
    "CoresetSelection",
    "ReferenceMemoryManifest",
    "ReferenceNeighbor",
    "ReferenceSearchResult",
    "ReferenceSimilaritySearch",
    "ReferenceVectorRecord",
    "LightweightVisualRepresentationProvider",
    "RepresentationBatch",
    "RepresentationProviderConfig",
    "RepresentationProviderMetadata",
    "RepresentationRecord",
    "VisualRepresentationProvider",
    "QueryPatchRecord",
    "PatchAnomalyScore",
    "ImageAnomalyScore",
    "SpatialAnomalyMap",
    "ReferenceEvidence",
    "ReferenceScoringProvenance",
    "ReferenceScoringResult",
    "ReferenceScoringSummary",
    "VisualArtifactManifest",
    "VisualBackendCapabilities",
    "VisualConfigurationError",
    "VisualContractVersionError",
    "VisualDatasetRole",
    "VisualDatasetFingerprint",
    "VisualDatasetRoleError",
    "VisualEngineConfig",
    "VisualReferenceScoringConfig",
    "VisualEngineError",
    "VisualEngineRequest",
    "VisualEngineResult",
    "VisualExecutionMode",
    "VisualIntegrityError",
    "VisualManifestError",
    "VisualProvisioningError",
    "VisualReproducibilityManifest",
    "VisualFileFingerprint",
    "deserialize_artifact_manifest",
    "deserialize_reproducibility_manifest",
    "deserialize_reference_memory_manifest",
    "build_reference_memory",
    "derive_reference_memory_id",
    "fingerprint_configuration",
    "fingerprint_visual_dataset",
    "fingerprint_visual_directory",
    "normalize_relative_path",
    "load_reference_memory",
    "read_artifact_manifest",
    "read_reproducibility_manifest",
    "serialize_artifact_manifest",
    "serialize_reproducibility_manifest",
    "select_reference_coreset",
    "serialize_reference_memory_manifest",
    "sha256_file",
    "sha256_stream",
    "validate_artifact_integrity",
    "validate_reference_records",
    "validate_reference_memory",
    "write_manifest",
    "build_spatial_maps",
    "publish_scoring_artifacts",
    "score_reference_anomalies",
    "validate_scoring_artifacts",
    "create_visual_representation_provider",
]
