"""Versioned contracts and reproducibility foundations for ADE visual workflows."""

from ade.visual.config import VISUAL_ENGINE_SCHEMA_VERSION, VisualEngineConfig
from ade.visual.contracts import (
    VisualArtifactManifest,
    VisualBackendCapabilities,
    VisualDatasetRole,
    VisualEngineRequest,
    VisualEngineResult,
    VisualExecutionMode,
    VisualReproducibilityManifest,
)
from ade.visual.errors import (
    VisualConfigurationError,
    VisualContractVersionError,
    VisualDatasetRoleError,
    VisualEngineError,
    VisualIntegrityError,
    VisualManifestError,
    VisualProvisioningError,
)
from ade.visual.fingerprints import (
    VisualDatasetFingerprint,
    VisualFileFingerprint,
    fingerprint_configuration,
    fingerprint_visual_dataset,
    fingerprint_visual_directory,
    normalize_relative_path,
    sha256_file,
    sha256_stream,
)
from ade.visual.manifests import (
    deserialize_artifact_manifest,
    deserialize_reproducibility_manifest,
    read_artifact_manifest,
    read_reproducibility_manifest,
    serialize_artifact_manifest,
    serialize_reproducibility_manifest,
    validate_artifact_integrity,
    write_manifest,
)
from ade.visual.reference_contracts import (
    REFERENCE_MEMORY_SCHEMA_VERSION,
    LoadedReferenceMemory,
    ReferenceMemoryManifest,
    ReferenceNeighbor,
    ReferenceSearchResult,
    ReferenceVectorRecord,
    validate_reference_records,
)
from ade.visual.reference_memory import (
    build_reference_memory,
    derive_reference_memory_id,
    deserialize_reference_memory_manifest,
    load_reference_memory,
    serialize_reference_memory_manifest,
    validate_reference_memory,
)

__all__ = [
    "VISUAL_ENGINE_SCHEMA_VERSION",
    "REFERENCE_MEMORY_SCHEMA_VERSION",
    "LoadedReferenceMemory",
    "ReferenceMemoryManifest",
    "ReferenceNeighbor",
    "ReferenceSearchResult",
    "ReferenceVectorRecord",
    "VisualArtifactManifest",
    "VisualBackendCapabilities",
    "VisualConfigurationError",
    "VisualContractVersionError",
    "VisualDatasetRole",
    "VisualDatasetFingerprint",
    "VisualDatasetRoleError",
    "VisualEngineConfig",
    "VisualEngineError",
    "VisualEngineRequest",
    "VisualEngineResult",
    "VisualExecutionMode",
    "VisualIntegrityError",
    "VisualManifestError",
    "VisualProvisioningError",
    "VisualReproducibilityManifest",
    "VisualFileFingerprint",
    "deserialize_artifact_manifest",
    "deserialize_reproducibility_manifest",
    "deserialize_reference_memory_manifest",
    "build_reference_memory",
    "derive_reference_memory_id",
    "fingerprint_configuration",
    "fingerprint_visual_dataset",
    "fingerprint_visual_directory",
    "normalize_relative_path",
    "load_reference_memory",
    "read_artifact_manifest",
    "read_reproducibility_manifest",
    "serialize_artifact_manifest",
    "serialize_reproducibility_manifest",
    "serialize_reference_memory_manifest",
    "sha256_file",
    "sha256_stream",
    "validate_artifact_integrity",
    "validate_reference_records",
    "validate_reference_memory",
    "write_manifest",
]
